export { DetalleFactura } from './models/detalle-factura';
export { NewDetalleFactura } from './models/new-detalle-factura';
export { FacturaWithRelations } from './models/factura-with-relations';
export { ProductosWithRelations } from './models/productos-with-relations';
export { DetalleFacturaWithRelations } from './models/detalle-factura-with-relations';
export { DetalleFacturaPartial } from './models/detalle-factura-partial';
export { Factura } from './models/factura';
export { NewFactura } from './models/new-factura';
export { FacturaPartial } from './models/factura-partial';
export { Productos } from './models/productos';
export { NewProductos } from './models/new-productos';
export { ProductosPartial } from './models/productos-partial';
export { Count as LoopbackCount } from './models/loopback/count';
export { PingResponse } from './models/ping-response';
